# Used by app
[security.password]
# Critical: This value must be kept secret and should be changed in production
# Losing or changing this value will invalidate all existing password hashes
# IMPORTANT: Replace the placeholder below with your own secure random string
# Recommended: Use a cryptographically secure random generator to create a
# string of at least 32 characters including numbers, letters, and symbols
PASSWORD_PEPPER = "REPLACE_THIS_WITH_YOUR_OWN_SECRET_PEPPER_VALUE"

# Used by app
[security.session]
# Recommended: Use a cryptographically secure random generator to create a
# string of at least 32 characters including numbers, letters, and symbols
JWT_SECRET = "REPLACE_THIS_WITH_YOUR_OWN_SECRET_VALUE"
# JWT_ALGORITHM can be set to "HS256", "HS384", "HS512", "RS256", "RS384", "RS512"
JWT_ALGORITHM = "HS256"
# SESSION_TTL_MIN must be at least 1 (number of minutes)
SESSION_TTL_MIN = 5
# SESSION_REFRESH_THRESHOLD must be a number (fraction, 0 < fraction < 1)
SESSION_REFRESH_THRESHOLD = 0.2

# Used by app
[security.cookies]
# Secure can be set to 0 or 1
# Choose 1 for production (secure=True, samesite="Strict")
SECURE = 0

# Logging settings
# Used by app
[logging]
# Level can be set to "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
LOG_LEVEL = "DEBUG"

# Used by app
# Used by docker-compose
[uvicorn]
UVICORN_HOST = "0.0.0.0"
UVICORN_PORT = 8000
UVICORN_RELOAD = false

# Used by app
# Used by docker-compose
[db.postgres]
# Specify as in Docker network
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "MBPNe6TJxHPiTN0sG85YzmN4p0koW5QO"
POSTGRES_DB = "app"
# Set host to localhost for local dev
# Don't forget to regenerate dotenv
# Don't forget to apply alembic rev
# Set host to postgres for prod
POSTGRES_HOST = "db"
#POSTGRES_HOST = "db"
POSTGRES_PORT = 5432

# Used by app
[db.sqla_engine]
SQLA_ECHO = false
SQLA_ECHO_POOL = false
SQLA_POOL_SIZE = 50
SQLA_MAX_OVERFLOW = 10

# Used by Makefile
# Used by Dockerfile
# Used by docker-compose
# No '/' after dir name !
[structure]
CONFIG_TOML = "config.toml"
PYPROJECT_TOML = "pyproject.toml"

# CORS
[security.cors]
BACKEND_CORS_ORIGINS = "http://localhost,https://localhost,http://localhost.kg.com"
