# Used by app
[security.keycloak]
AUTH_URL = "http://localhost:8080/realms/contraction_tracker/protocol/openid-connect/auth"
TOKEN_URL = "http://localhost:8080/realms/contraction_tracker/protocol/openid-connect/token"
REFRESH_URL = "http://localhost:8080/realms/contraction_tracker/protocol/openid-connect/token"
KEYCLOAK_SERVER_URL = "http://localhost:8080"
KEYCLOAK_REALM  = "contraction_tracker"
KEYCLOAK_CLIENT_ID  = "contraction_tracker_backend"
KEYCLOAK_CLIENT_SECRET  = "lVAF65cRED5tKkWHlSkIJnVSdwOMDqpl"
# JWT_ALGORITHM can be set to "HS256", "HS384", "HS512", "RS256", "RS384", "RS512"
JWT_ALGORITHM = "HS256"

# Used by app
[security.cookies]
# Secure can be set to 0 or 1
# Choose 1 for production (secure=True, samesite="Strict")
SECURE = 0

# Logging settings
# Used by app
[logging]
# Level can be set to "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
LOG_LEVEL = "INFO"

# Used by app
# Used by docker-compose
[uvicorn]
UVICORN_HOST = "0.0.0.0"
UVICORN_PORT = 8000
UVICORN_RELOAD = false

# Used by app
# Used by docker-compose
[db.postgres]
# Specify as in Docker network
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "MBPNe6TJxHPiTN0sG85YzmN4p0koW5QO"
POSTGRES_DB = "app"
# Set host to localhost for local dev
# Don't forget to regenerate dotenv
# Don't forget to apply alembic rev
# Set host to postgres for prod
POSTGRES_HOST = "db"
#POSTGRES_HOST = "db"
POSTGRES_PORT = 5432

# Used by app
[db.sqla_engine]
SQLA_ECHO = false
SQLA_ECHO_POOL = false
SQLA_POOL_SIZE = 50
SQLA_MAX_OVERFLOW = 10

# Used by Makefile
# Used by Dockerfile
# Used by docker-compose
# No '/' after dir name !
[structure]
CONFIG_TOML = "config.toml"
PYPROJECT_TOML = "pyproject.toml"

# CORS
[security.cors]
BACKEND_CORS_ORIGINS = "http://localhost,https://localhost,http://localhost.kg.com"

# Used by App
[notification.email]
SMTP_HOST = "mailcatcher"
SMTP_USER = ""
SMTP_PASSWORD = ""
EMAILS_FROM_EMAIL = "noreply@example.com"
EMAILS_FROM_NAME = "kieran"
SMTP_SSL = false
SMTP_TLS = false
SMTP_PORT = 1025
