services:

  labour-consumer:
    image: '${DOCKER_IMAGE_REPOSITORY}/${DOCKER_IMAGE_LABOUR_SERVICE?unset}:${TAG-latest}'
    restart: always
    env_file:
      - ./labour_service/.env
    command: [ "python", "-m", "src.run_consumer" ]
    networks:
      - default
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_application_credentials
    secrets:
      - gcp_application_credentials

  notification-consumer:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${DOCKER_IMAGE_NOTIFICATION_SERVICE?unset}:${TAG-latest}'
    restart: always
    env_file:
      - ./notification_service/.env
    command: [ "python", "-m", "src.run_consumer" ]
    networks:
      - default
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_application_credentials
    secrets:
      - gcp_application_credentials

  keycloak:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${STACK_NAME?unset}-keycloak:${TAG-latest}'
    command: start
    environment:
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: ${POSTGRES_HOST}
      KC_DB_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: auth.${DOMAIN?unset}
      PROXY_ADDRESS_FORWARDING: true
    restart: always
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      # --- Middlewares for Keycloak Admin Access Control ---
      # Redirect Middleware to hide admin
      - traefik.http.middlewares.${STACK_NAME?unset}-keycloak-admin-redirect.redirectregex.regex=^(https?://)?auth\.${DOMAIN?unset}/admin(/.*)?$$
      - traefik.http.middlewares.${STACK_NAME?unset}-keycloak-admin-redirect.redirectregex.replacement=${FRONTEND_URL?unset}
      - traefik.http.middlewares.${STACK_NAME?unset}-keycloak-admin-redirect.redirectregex.permanent=false

      # --- Routers for Keycloak ---
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-entry-http.rule=Host(`auth.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-entry-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-entry-http.middlewares=https-redirect@docker

      # Router 1: Admin access - Redirect
      # Matches auth.{DOMAIN}/admin/master/*
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-admin-redirect-https.rule=Host(`auth.${DOMAIN?unset}`) && PathPrefix(`/admin/master`)
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-admin-redirect-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-admin-redirect-https.priority=10
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-admin-redirect-https.tls=true
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-admin-redirect-https.tls.certresolver=le
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-admin-redirect-https.middlewares=${STACK_NAME?unset}-keycloak-admin-redirect@docker
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-admin-redirect-https.service=noop@internal

      # Router 2: General Keycloak Access
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-main-https.rule=Host(`auth.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-main-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-main-https.priority=1
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-main-https.tls=true
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-main-https.tls.certresolver=le
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-main-https.service=${STACK_NAME?unset}-keycloak-svc@docker

      # --- Service Definition for Keycloak ---
      - traefik.http.services.${STACK_NAME?unset}-keycloak-svc.loadbalancer.server.port=8080
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import:ro

networks:
  traefik-public:
    external: true

secrets:
  gcp_application_credentials:
    file: /home/kieran/.config/gcloud/application_default_credentials.json
