services:

  labour-consumer:
    image: '${DOCKER_IMAGE_REPOSITORY}/${DOCKER_IMAGE_LABOUR_SERVICE?unset}:${TAG-latest}'
    restart: always
    env_file:
      - ./labour_service/.env
    command: [ "python", "-m", "src.run_consumer" ]
    networks:
      - default
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_application_credentials
    secrets:
      - gcp_application_credentials

  notification-consumer:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${DOCKER_IMAGE_NOTIFICATION_SERVICE?unset}:${TAG-latest}'
    restart: always
    env_file:
      - ./notification_service/.env
    command: [ "python", "-m", "src.run_consumer" ]
    networks:
      - default
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_application_credentials
    secrets:
      - gcp_application_credentials

  keycloak:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${STACK_NAME?unset}-keycloak:${TAG-latest}'
    command: start
    environment:
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: ${POSTGRES_HOST}
      KC_DB_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: auth.${DOMAIN?unset}
      PROXY_ADDRESS_FORWARDING: true
    restart: always
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      # Keycloak application routes
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-http.rule=Host(`auth.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-http.middlewares=https-redirect
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-https.rule=Host(`auth.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-https.tls=true
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-https.tls.certresolver=le
      - traefik.http.services.${STACK_NAME?unset}-keycloak.loadbalancer.server.port=8080
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import:ro

networks:
  traefik-public:
    external: true

secrets:
  gcp_application_credentials:
    file: /home/kieran/.config/gcloud/application_default_credentials.json
