services:

  db:
    image: postgres:16.2
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

  backend-pre-start:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
    command: [ "alembic", "upgrade", "head" ]

  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    restart: always
    networks:
      - traefik-public
      - default
    depends_on:
      db:
        condition: service_healthy
        restart: true
      backend-pre-start:
        condition: service_completed_successfully
        restart: false
      keycloak:
        condition: service_started
    env_file:
      - .env
    ports:
      - "${UVICORN_PORT}:${UVICORN_PORT}"
    environment:
      - DOMAIN=${DOMAIN}
      - ENVIRONMENT=${ENVIRONMENT}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - SECRET_KEY=${SECRET_KEY?Variable not set}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - SENTRY_DSN=${SENTRY_DSN}
    volumes:
      - ./${SRC_DIR}:/app/${SRC_DIR}
      - ./${CONFIG_TOML}:/${CONFIG_TOML}
      - ./.env:/app/.env
    command: [ "python", "-m", "app.run" ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.services.${STACK_NAME?Variable not set}-backend.loadbalancer.server.port=8000
      - traefik.http.routers.${STACK_NAME?Variable not set}-backend-http.rule=Host(`api.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-backend-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME?Variable not set}-backend-https.rule=Host(`api.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-backend-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?Variable not set}-backend-https.tls=true
      - traefik.http.routers.${STACK_NAME?Variable not set}-backend-https.tls.certresolver=le
      - traefik.http.routers.${STACK_NAME?Variable not set}-backend-http.middlewares=https-redirect

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start
    environment:
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL: jdbc:postgresql://db:${POSTGRES_PORT}/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      # Keycloak application routes
      - traefik.http.routers.${STACK_NAME?Variable not set}-keycloak-http.rule=Host(`keycloak.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-keycloak-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME?Variable not set}-keycloak-http.middlewares=https-redirect
      - traefik.http.routers.${STACK_NAME?Variable not set}-keycloak-https.rule=Host(`keycloak.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-keycloak-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?Variable not set}-keycloak-https.tls=true
      - traefik.http.routers.${STACK_NAME?Variable not set}-keycloak-https.tls.certresolver=le
      - traefik.http.services.${STACK_NAME?Variable not set}-keycloak.loadbalancer.server.port=8080
      # Keycloak management routes
      - traefik.http.routers.${STACK_NAME?Variable not set}-keycloak-admin-http.rule=Host(`keycloak.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-keycloak-admin-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME?Variable not set}-keycloak-admin-http.middlewares=https-redirect
      - traefik.http.routers.${STACK_NAME?Variable not set}-keycloak-admin-https.rule=Host(`keycloak.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-keycloak-admin-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?Variable not set}-keycloak-admin-https.tls=true
      - traefik.http.routers.${STACK_NAME?Variable not set}-keycloak-admin-https.tls.certresolver=le
      - traefik.http.services.${STACK_NAME?Variable not set}-keycloak.loadbalancer.server.port=9000


  backend-base:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}'
    build:
      context: .
      target: production
  
  backend-dev:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}-dev'
    build:
      context: .
      target: dev

volumes:
  app-db-data:

networks:
  traefik-public:
    # Allow setting it to false for testing
    external: true
