services:
  frontend:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${DOCKER_IMAGE_FRONTEND?unset}:${TAG-latest}'
    restart: always
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.${STACK_NAME?unset}-frontend.loadbalancer.server.port=80

      - traefik.http.routers.${STACK_NAME?unset}-frontend-http.rule=Host(`track.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-frontend-http.entrypoints=http

      - traefik.http.routers.${STACK_NAME?unset}-frontend-https.rule=Host(`track.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-frontend-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?unset}-frontend-https.tls=true
      - traefik.http.routers.${STACK_NAME?unset}-frontend-https.tls.certresolver=le

      # Enable redirection for HTTP and HTTPS
      - traefik.http.routers.${STACK_NAME?unset}-frontend-http.middlewares=https-redirect

  marketing:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${DOCKER_IMAGE_MARKETING?unset}:${TAG-latest}'
    restart: always
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.${STACK_NAME?unset}-marketing.loadbalancer.server.port=81

      - traefik.http.routers.${STACK_NAME?unset}-marketing-http.rule=Host(`${DOMAIN?unset}`) || Host(`www.${DOMAIN}`)
      - traefik.http.routers.${STACK_NAME?unset}-marketing-http.entrypoints=http

      - traefik.http.routers.${STACK_NAME?unset}-marketing-https.rule=Host(`${DOMAIN?unset}`) || Host(`www.${DOMAIN}`)
      - traefik.http.routers.${STACK_NAME?unset}-marketing-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?unset}-marketing-https.tls=true
      - traefik.http.routers.${STACK_NAME?unset}-marketing-https.tls.certresolver=le

      # Enable redirection for HTTP and HTTPS
      - traefik.http.routers.${STACK_NAME?unset}-marketing-http.middlewares=https-redirect
      - traefik.http.middlewares.mywwwremove.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwremove.redirectregex.replacement=https://$${1}
      - traefik.http.routers.${STACK_NAME?unset}-marketing.middlewares=mywwwremove

networks:
  traefik-public:
    external: true
