services:

  labour-service:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${DOCKER_IMAGE_LABOUR_SERVICE?unset}:${TAG-latest}'
    restart: always
    networks:
      - traefik-public
      - default
    depends_on:
      labour-service-pre-start:
        condition: service_completed_successfully
        restart: false
    env_file:
      - ./labour_service/.env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_application_credentials
    secrets:
      - gcp_application_credentials
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.${STACK_NAME?unset}-backend.loadbalancer.server.port=8000

      - traefik.http.routers.${STACK_NAME?unset}-backend-http.rule=Host(`api.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-backend-http.entrypoints=http

      - traefik.http.routers.${STACK_NAME?unset}-backend-https.rule=Host(`api.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-backend-https.entrypoints=https

      - traefik.http.routers.${STACK_NAME?unset}-backend-https.tls=true
      - traefik.http.routers.${STACK_NAME?unset}-backend-https.tls.certresolver=le
      - traefik.http.routers.${STACK_NAME?unset}-backend-http.middlewares=https-redirect

  labour-service-pre-start:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${DOCKER_IMAGE_LABOUR_SERVICE?unset}-alembic:${TAG-latest}'
    restart: "no"
    env_file:
      - ./labour_service/.env

  notification-service:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${DOCKER_IMAGE_NOTIFICATION_SERVICE?unset}:${TAG-latest}'
    restart: always
    networks:
      - traefik-public
      - default
    depends_on:
      notification-service-pre-start:
        condition: service_completed_successfully
        restart: false
    env_file:
      - ./notification_service/.env
    ports:
      - "8001:8001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/api/v1/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_application_credentials
    secrets:
      - gcp_application_credentials
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.${STACK_NAME?unset}-notifications.loadbalancer.server.port=8001

      - traefik.http.routers.${STACK_NAME?unset}-notifications-http.rule=Host(`notifications.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-notifications-http.entrypoints=http

      - traefik.http.routers.${STACK_NAME?unset}-notifications-https.rule=Host(`notifications.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-notifications-https.entrypoints=https

      - traefik.http.routers.${STACK_NAME?unset}-notifications-https.tls=true
      - traefik.http.routers.${STACK_NAME?unset}-notifications-https.tls.certresolver=le
      - traefik.http.routers.${STACK_NAME?unset}-notifications-http.middlewares=https-redirect

  notification-service-pre-start:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${DOCKER_IMAGE_NOTIFICATION_SERVICE?unset}-alembic:${TAG-latest}'
    restart: "no"
    env_file:
      - ./notification_service/.env

  contact-service:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${DOCKER_IMAGE_CONTACT_SERVICE?unset}:${TAG-latest}'
    restart: always
    networks:
      - traefik-public
      - default
    depends_on:
      contact-service-pre-start:
        condition: service_completed_successfully
        restart: false
    env_file:
      - ./contact_service/.env
    ports:
      - "8002:8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_application_credentials
    secrets:
      - gcp_application_credentials
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.${STACK_NAME?unset}-contact.loadbalancer.server.port=8002

      - traefik.http.routers.${STACK_NAME?unset}-contact-http.rule=Host(`contact.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-contact-http.entrypoints=http

      - traefik.http.routers.${STACK_NAME?unset}-contact-https.rule=Host(`contact.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-contact-https.entrypoints=https

      - traefik.http.routers.${STACK_NAME?unset}-contact-https.tls=true
      - traefik.http.routers.${STACK_NAME?unset}-contact-https.tls.certresolver=le
      - traefik.http.routers.${STACK_NAME?unset}-contact-http.middlewares=https-redirect

  contact-service-pre-start:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${DOCKER_IMAGE_CONTACT_SERVICE?unset}-alembic:${TAG-latest}'
    restart: "no"
    env_file:
      - ./contact_service/.env

  labour-consumer:
    image: '${DOCKER_IMAGE_REPOSITORY}/${DOCKER_IMAGE_LABOUR_SERVICE?unset}:${TAG-latest}'
    restart: always
    env_file:
      - ./labour_service/.env
    command: [ "python", "-m", "src.run_consumer" ]
    networks:
      - default
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_application_credentials
    secrets:
      - gcp_application_credentials

  notification-consumer:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${DOCKER_IMAGE_NOTIFICATION_SERVICE?unset}:${TAG-latest}'
    restart: always
    env_file:
      - ./notification_service/.env
    command: [ "python", "-m", "src.run_consumer" ]
    networks:
      - default
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_application_credentials
    secrets:
      - gcp_application_credentials

  keycloak:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${STACK_NAME?unset}-keycloak:${TAG-latest}'
    command: start
    environment:
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: ${POSTGRES_HOST}
      KC_DB_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_STRICT: false
    restart: always
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      # Keycloak application routes
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-http.rule=Host(`auth.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-http.middlewares=https-redirect
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-https.rule=Host(`auth.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-https.tls=true
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-https.tls.certresolver=le
      - traefik.http.services.${STACK_NAME?unset}-keycloak.loadbalancer.server.port=8080
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import:ro

  frontend:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${DOCKER_IMAGE_FRONTEND?unset}:${TAG-latest}'
    restart: always
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.${STACK_NAME?unset}-frontend.loadbalancer.server.port=80

      - traefik.http.routers.${STACK_NAME?unset}-frontend-http.rule=Host(`track.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-frontend-http.entrypoints=http

      - traefik.http.routers.${STACK_NAME?unset}-frontend-https.rule=Host(`track.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-frontend-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?unset}-frontend-https.tls=true
      - traefik.http.routers.${STACK_NAME?unset}-frontend-https.tls.certresolver=le

      # Enable redirection for HTTP and HTTPS
      - traefik.http.routers.${STACK_NAME?unset}-frontend-http.middlewares=https-redirect

  marketing:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${DOCKER_IMAGE_MARKETING?unset}:${TAG-latest}'
    restart: always
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.${STACK_NAME?unset}-marketing.loadbalancer.server.port=81

      - traefik.http.routers.${STACK_NAME?unset}-marketing-http.rule=Host(`${DOMAIN?unset}`) || Host(`www.${DOMAIN}`)
      - traefik.http.routers.${STACK_NAME?unset}-marketing-http.entrypoints=http

      - traefik.http.routers.${STACK_NAME?unset}-marketing-https.rule=Host(`${DOMAIN?unset}`) || Host(`www.${DOMAIN}`)
      - traefik.http.routers.${STACK_NAME?unset}-marketing-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?unset}-marketing-https.tls=true
      - traefik.http.routers.${STACK_NAME?unset}-marketing-https.tls.certresolver=le

      # Enable redirection for HTTP and HTTPS
      - traefik.http.routers.${STACK_NAME?unset}-marketing-http.middlewares=https-redirect
      - traefik.http.middlewares.mywwwremove.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwremove.redirectregex.replacement=https://$${1}
      - traefik.http.routers.${STACK_NAME?unset}-marketing.middlewares=mywwwremove

  valkey:
    image: valkey/valkey:latest
    command: valkey-server --port ${REDIS_PORT?unset} --requirepass ${REDIS_PASSWORD?unset} --save
    volumes:
      - valkey-cache:/data

volumes:
  valkey-cache:

networks:
  traefik-public:
    # Allow setting it to false for testing
    external: true

secrets:
  gcp_application_credentials:
    file: /home/kieran/.config/gcloud/application_default_credentials.json
