services:

  labour-service:
    image: '${DOCKER_IMAGE_LABOUR_SERVICE?Variable not set}:latest'
    build:
      context: ./labour_service
      target: development
      secrets:
        - artifact_registry_token
    restart: "no"
    networks:
      - traefik-public
      - default
    depends_on:
      db:
        condition: service_healthy
        restart: true
      labour-service-pre-start:
        condition: service_completed_successfully
        restart: false
    env_file:
      - ./labour_service/.env
    environment:
      - PUBSUB_EMULATOR_HOST=pub-sub-emulator:8085
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./labour_service/app:/app/app
      - ./labour_service/config.toml/:/app/config.toml
    command: [ "debugpy", "--listen", "0.0.0.0:5678", "-m", "app.run" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/health" ]
      interval: 30s
      timeout: 5s
      retries: 5

  labour-service-pre-start:
    image: '${DOCKER_IMAGE_LABOUR_SERVICE?Variable not set}-alembic:latest'
    build:
      context: ./labour_service
      target: migrations
      secrets:
        - artifact_registry_token
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - ./labour_service/.env

  notification-service:
    image: '${DOCKER_IMAGE_NOTIFICATION_SERVICE?Variable not set}:latest'
    build:
      context: ./notification_service
      target: http
      secrets:
        - artifact_registry_token
    restart: "no"
    networks:
      - traefik-public
      - default
    depends_on:
      db:
        condition: service_healthy
        restart: true
      notification-service-pre-start:
        condition: service_completed_successfully
        restart: false
    env_file:
      - ./notification_service/.env
    environment:
      - PUBSUB_EMULATOR_HOST=pub-sub-emulator:8085
    ports:
      - "8001:8001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/api/v1/health" ]
      interval: 30s
      timeout: 5s
      retries: 5

  notification-service-pre-start:
    image: '${DOCKER_IMAGE_NOTIFICATION_SERVICE?Variable not set}-alembic:latest'
    build:
      context: ./notification_service
      target: migrations
      secrets:
        - artifact_registry_token
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - ./notification_service/.env

  db:
    image: postgres:16.2
    restart: "no"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
      - ./keycloak/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    command: 
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=1"
      - "-c"
      - "max_replication_slots=1"

  labour-consumer:
    image: '${DOCKER_IMAGE_LABOUR_SERVICE?Variable not set}:latest'
    restart: "no"
    env_file:
      - ./labour_service/.env
    environment:
      - PUBSUB_EMULATOR_HOST=pub-sub-emulator:8085
    command: [ "python", "-m", "app.run_consumer" ]
    networks:
      - default

  notification-consumer:
    image: '${DOCKER_IMAGE_NOTIFICATION_SERVICE?Variable not set}:latest'
    restart: "no"
    env_file:
      - ./notification_service/.env
    environment:
      - PUBSUB_EMULATOR_HOST=pub-sub-emulator:8085
    command: [ "python", "-m", "src.run_consumer" ]
    networks:
      - default

  keycloak:
    image: '${STACK_NAME?Variable not set}-keycloak:latest'
    build:
      context: ./keycloak
    restart: "no"
    environment:
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: ${POSTGRES_HOST}
      KC_DB_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_STRICT: false
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - "8080:8080"
      - "9000:9000"
    command:
      - start-dev
      - --import-realm
    networks:
      - traefik-public
      - default
    volumes:
      - ./keycloak/labour_tracker_theme:/opt/keycloak/themes/labour_tracker_theme
      - ./keycloak/realms:/opt/keycloak/data/import:ro

  pub-sub-emulator:
    image: google/cloud-sdk:latest
    command: ["gcloud", "beta", "emulators", "pubsub", "start", "--host-port=0.0.0.0:8085", "--project=test"]
    ports:
      - "8085:8085"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/v1/projects/test/schemas"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pub-sub-init:
    image: curlimages/curl:latest
    depends_on:
      pub-sub-emulator:
        condition: service_healthy
    volumes:
      - ./dev/pub-sub-init.sh:/pubsub-init.sh
    entrypoint: ["/bin/sh", "/pubsub-init.sh"]
    environment:
      - PUBSUB_EMULATOR_HOST=pub-sub-emulator:8085
      - PUBSUB_PROJECT_ID=test

  frontend:
    image: '${DOCKER_IMAGE_FRONTEND?Variable not set}:latest'
    build:
      context: ./frontend
      # target: build-stage
      args:
        - VITE_API_URL=http://localhost:8000
        - NODE_ENV=development
        - VITE_API_URL=${VITE_API_URL}
        - VITE_KEYCLOAK_AUTHORITY=${VITE_KEYCLOAK_AUTHORITY}
        - VITE_KEYCLOAK_METADATA_URL=${VITE_KEYCLOAK_METADATA_URL}
        - VITE_KEYCLOAK_CLIENT_ID=${VITE_KEYCLOAK_CLIENT_ID}
        - VITE_POST_LOGOUT_REDIRECT=${VITE_POST_LOGOUT_REDIRECT}
    restart: "no"
    networks:
      - traefik-public
      - default
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
      - ./.env:/app/.env
    # command: [ "npm", "run", "dev" ]

  marketing:
    image: '${DOCKER_IMAGE_MARKETING?Variable not set}:latest'
    build:
      context: ./marketing
      target: build-stage
      args:
        - NODE_ENV=development
        - BACKEND_API_URL=${BACKEND_API_URL?variable not set}
        - INSTAGRAM_URL=${INSTAGRAM_URL?variable not set}
        - FRONTEND_URL=${FRONTEND_HOST?variable not set}
    restart: "no"
    networks:
      - traefik-public
      - default
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_API_URL=${BACKEND_API_URL?variable not set}
      - NEXT_PUBLIC_FRONTEND_URL=${FRONTEND_HOST?variable not set}
      - NEXT_PUBLIC_INSTAGRAM_URL=${INSTAGRAM_URL?variable not set}
    command: [ "npm", "run", "dev" ]

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  app-db-data:

networks:
  traefik-public:
    external: false

secrets:
  artifact_registry_token:
    file: .artifact-registry-token
