services:

  labour-service:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${DOCKER_IMAGE_LABOUR_SERVICE?unset}:${TAG-latest}'
    restart: always
    networks:
      - traefik-public
      - default
    depends_on:
      labour-service-pre-start:
        condition: service_completed_successfully
        restart: false
    env_file:
      - ./labour_service/.env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_application_credentials
    secrets:
      - gcp_application_credentials
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.${STACK_NAME?unset}-backend.loadbalancer.server.port=8000

      - traefik.http.routers.${STACK_NAME?unset}-backend-http.rule=Host(`api.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-backend-http.entrypoints=http

      - traefik.http.routers.${STACK_NAME?unset}-backend-https.rule=Host(`api.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-backend-https.entrypoints=https

      - traefik.http.routers.${STACK_NAME?unset}-backend-https.tls=true
      - traefik.http.routers.${STACK_NAME?unset}-backend-https.tls.certresolver=le
      - traefik.http.routers.${STACK_NAME?unset}-backend-http.middlewares=https-redirect

  labour-service-pre-start:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${DOCKER_IMAGE_LABOUR_SERVICE?unset}-alembic:${TAG-latest}'
    restart: "no"
    env_file:
      - ./labour_service/.env

  labour-consumer:
    image: '${DOCKER_IMAGE_REPOSITORY}/${DOCKER_IMAGE_LABOUR_SERVICE?unset}:${TAG-latest}'
    restart: always
    env_file:
      - ./labour_service/.env
    command: [ "python", "-m", "src.run_consumer" ]
    networks:
      - default
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_application_credentials
    secrets:
      - gcp_application_credentials

  notification-consumer:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${DOCKER_IMAGE_NOTIFICATION_SERVICE?unset}:${TAG-latest}'
    restart: always
    env_file:
      - ./notification_service/.env
    command: [ "python", "-m", "src.run_consumer" ]
    networks:
      - default
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_application_credentials
    secrets:
      - gcp_application_credentials

  keycloak:
    image: '${DOCKER_IMAGE_REPOSITORY?unset}/${STACK_NAME?unset}-keycloak:${TAG-latest}'
    command: start
    environment:
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: ${POSTGRES_HOST}
      KC_DB_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_STRICT: false
    restart: always
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      # Keycloak application routes
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-http.rule=Host(`auth.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-http.middlewares=https-redirect
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-https.rule=Host(`auth.${DOMAIN?unset}`)
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-https.tls=true
      - traefik.http.routers.${STACK_NAME?unset}-keycloak-https.tls.certresolver=le
      - traefik.http.services.${STACK_NAME?unset}-keycloak.loadbalancer.server.port=8080
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import:ro

networks:
  traefik-public:
    external: true

secrets:
  gcp_application_credentials:
    file: /home/kieran/.config/gcloud/application_default_credentials.json
