services:

  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:latest'
    build:
      context: ./backend
      target: dev
    restart: "no"
    networks:
      - traefik-public
      - default
    depends_on:
      db:
        condition: service_healthy
        restart: true
      backend-pre-start:
        condition: service_completed_successfully
        restart: false
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./backend/app:/app/app
      - ./backend/config.toml/:/app/config.toml
    command: [ "debugpy", "--listen", "0.0.0.0:5678", "-m", "app.run" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/health" ]
      interval: 30s
      timeout: 5s
      retries: 5

  backend-pre-start:
    image: '${DOCKER_IMAGE_REPOSITORY}${DOCKER_IMAGE_BACKEND?Variable not set}:latest'
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - ./backend/.env
    command: [ "alembic", "upgrade", "head" ]

  notification-service:
    image: '${DOCKER_IMAGE_NOTIFICATIONS?Variable not set}:latest'
    build:
      context: ./notification_service
      target: dev
    restart: "no"
    networks:
      - traefik-public
      - default
    depends_on:
      db:
        condition: service_healthy
        restart: true
      notification-service-pre-start:
        condition: service_completed_successfully
        restart: false
    env_file:
      - ./notification_service/.env
    ports:
      - "8001:8001"
      - "5680:5680"
    volumes:
      - ./notification_service/app:/app/app
      - ./notification_service/config.toml/:/app/config.toml
    command: [ "debugpy", "--listen", "0.0.0.0:5680", "-m", "app.run" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/api/v1/health" ]
      interval: 30s
      timeout: 5s
      retries: 5

  notification-service-pre-start:
    image: '${DOCKER_IMAGE_NOTIFICATIONS?Variable not set}:latest'
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - ./notification_service/.env
    command: [ "alembic", "upgrade", "head" ]

  db:
    image: postgres:16.2
    restart: "no"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
      - ./keycloak/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    command: 
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=1"
      - "-c"
      - "max_replication_slots=1"

  labour-consumer:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:latest'
    restart: "no"
    depends_on:
      init-kafka:
        condition: service_completed_successfully
        restart: false
    env_file:
      - ./backend/.env
    ports:
      - "5679:5679"
    command: [ "debugpy", "--listen", "0.0.0.0:5679", "-m", "app.run_consumer" ]
    networks:
      - default

  notifications-consumer:
    image: '${DOCKER_IMAGE_NOTIFICATIONS?Variable not set}:latest'
    restart: "no"
    depends_on:
      init-kafka:
        condition: service_completed_successfully
        restart: false
    env_file:
      - ./notification_service/.env
    ports:
      - "5681:5681"
    command: [ "debugpy", "--listen", "0.0.0.0:5681", "-m", "app.run_consumer" ]
    networks:
      - default

  keycloak:
    image: '${STACK_NAME?Variable not set}-keycloak:latest'
    build:
      context: ./keycloak
    restart: "no"
    environment:
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: ${POSTGRES_HOST}
      KC_DB_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_STRICT: false
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - "8080:8080"
      - "9000:9000"
    command:
      - start-dev
      - --import-realm
    networks:
      - traefik-public
      - default
    volumes:
      - ./keycloak/labour_tracker_theme:/opt/keycloak/themes/labour_tracker_theme
      - ./keycloak/realms:/opt/keycloak/data/import:ro

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper-volume:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - default

  kafka:
    image: docker.io/bitnami/kafka:3.9
    container_name: kafka
    restart: always
    ports:
      - "9093:9093"
      - "9092:9092"
    volumes:
      - "kafka-volume:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list" ]
      interval: 15s
      timeout: 5s
      retries: 3

  init-kafka:
    image: docker.io/bitnami/kafka:3.9
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: [ '/bin/bash', '/setup.sh' ]
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS?variable not set}
      - KAFKA_TOPIC_PREFIX=${KAFKA_TOPIC_PREFIX?variable not set}
    volumes:
      - ./kafka/setup.sh:/setup.sh
    networks:
      - default

  frontend:
    image: '${DOCKER_IMAGE_FRONTEND?Variable not set}:latest'
    build:
      context: ./frontend
      target: build-stage
      args:
        - VITE_API_URL=http://localhost:8000
        - NODE_ENV=development
        - VITE_API_URL=${VITE_API_URL}
        - VITE_KEYCLOAK_AUTHORITY=${VITE_KEYCLOAK_AUTHORITY}
        - VITE_KEYCLOAK_METADATA_URL=${VITE_KEYCLOAK_METADATA_URL}
        - VITE_KEYCLOAK_CLIENT_ID=${VITE_KEYCLOAK_CLIENT_ID}
        - VITE_POST_LOGOUT_REDIRECT=${VITE_POST_LOGOUT_REDIRECT}
    restart: "no"
    networks:
      - traefik-public
      - default
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - ./.env:/app/.env
    command: [ "npm", "run", "dev" ]

  marketing:
    image: '${DOCKER_IMAGE_MARKETING?Variable not set}:latest'
    build:
      context: ./marketing
      target: build-stage
      args:
        - NODE_ENV=development
        - BACKEND_API_URL=${BACKEND_API_URL?variable not set}
        - INSTAGRAM_URL=${INSTAGRAM_URL?variable not set}
        - FRONTEND_URL=${FRONTEND_HOST?variable not set}
    restart: "no"
    networks:
      - traefik-public
      - default
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_API_URL=${BACKEND_API_URL?variable not set}
      - NEXT_PUBLIC_FRONTEND_URL=${FRONTEND_HOST?variable not set}
      - NEXT_PUBLIC_INSTAGRAM_URL=${INSTAGRAM_URL?variable not set}
    command: [ "npm", "run", "dev" ]

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
    networks:
      - default

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  app-db-data:
  kafka-volume:
  zookeeper-volume:


networks:
  traefik-public:
    external: false
