"""added payment plans

Revision ID: 215867225031
Revises: 9fcd6860e9d9
Create Date: 2025-03-10 13:38:30.848572

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "215867225031"
down_revision: str | None = "9fcd6860e9d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("labours", sa.Column("payment_plan", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("labours", "payment_plan")
    # ### end Alembic commands ###
