"""changes to subscriber and birthing person

Revision ID: 2cdc05281379
Revises: 965371c06219
Create Date: 2025-02-18 10:45:49.038814

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2cdc05281379"
down_revision: str | None = "965371c06219"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("birthing_persons", sa.Column("phone_number", sa.String(), nullable=True))
    op.add_column("birthing_persons", sa.Column("email", sa.String(), nullable=True))
    op.drop_column("birthing_persons", "subscribers")
    op.drop_column("subscribers", "contact_methods")
    op.drop_column("subscribers", "subscribed_to")
    sa.Enum("EMAIL", "SMS", name="contactmethod").drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("EMAIL", "SMS", name="contactmethod").create(op.get_bind())
    op.add_column(
        "subscribers",
        sa.Column(
            "subscribed_to", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "subscribers",
        sa.Column(
            "contact_methods",
            postgresql.ARRAY(
                postgresql.ENUM("EMAIL", "SMS", name="contactmethod", create_type=False)
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "birthing_persons",
        sa.Column(
            "subscribers", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("birthing_persons", "email")
    op.drop_column("birthing_persons", "phone_number")
    # ### end Alembic commands ###
