"""refactored announcements

Revision ID: 6894d33d448c
Revises: 46f0fbe55e13
Create Date: 2025-02-15 14:40:48.976332

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6894d33d448c"
down_revision: str | None = "46f0fbe55e13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("ANNOUNCEMENT", "STATUS_UPDATE", name="labour_update_type").create(op.get_bind())
    op.create_table(
        "labour_updates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "labour_update_type",
            postgresql.ENUM(
                "ANNOUNCEMENT", "STATUS_UPDATE", name="labour_update_type", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("labour_id", sa.UUID(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("sent_time", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["labour_id"], ["labours.id"], name=op.f("fk_labour_updates_labour_id_labours")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_labour_updates")),
    )
    op.drop_table("announcements")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "announcements",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("labour_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("message", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "sent_time", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["labour_id"], ["labours.id"], name="fk_announcements_labour_id_labours"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_announcements"),
    )
    op.drop_table("labour_updates")
    sa.Enum("ANNOUNCEMENT", "STATUS_UPDATE", name="labour_update_type").drop(op.get_bind())
    # ### end Alembic commands ###
