// This file is auto-generated by @hey-api/openapi-ts

export type ApproveSubscriberRequest = {
  subscription_id: string;
};

export type BlockSubscriberRequest = {
  subscription_id: string;
};

export type Body_login_api_v1_auth_login_post = {
  username: string;
  password: string;
};

export type CheckoutResponse = {
  id: string;
  url: string | null;
};

export type CompleteLabourRequest = {
  end_time?: string | null;
  notes?: string | null;
};

export type ContractionDTO = {
  id: string;
  labour_id: string;
  start_time: string;
  end_time: string;
  duration: number;
  intensity: number | null;
  notes: string | null;
  is_active: boolean;
};

export type CreateCheckoutRequest = {
  upgrade: string;
  subscription_id: string;
  success_url: string;
  cancel_url: string;
};

export type DeleteContractionRequest = {
  contraction_id: string;
};

export type DeleteLabourUpdateRequest = {
  labour_update_id: string;
};

export type EndContractionRequest = {
  intensity: number;
  end_time?: string | null;
  notes?: string | null;
};

export type ExceptionSchema = {
  description: string;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type LabourDTO = {
  id: string;
  birthing_person_id: string;
  current_phase: string;
  due_date: string;
  first_labour: boolean;
  labour_name: string | null;
  start_time: string | null;
  end_time: string | null;
  notes: string | null;
  recommendations: {
    [key: string]: boolean;
  };
  contractions: Array<ContractionDTO>;
  labour_updates: Array<LabourUpdateDTO>;
};

export type LabourListResponse = {
  labours: Array<LabourDTO>;
};

export type LabourResponse = {
  labour: LabourDTO;
};

export type LabourSubscriptionsResponse = {
  subscriptions: Array<SubscriptionDTO>;
  subscribers: Array<UserSummaryDTO>;
};

export type LabourSubscriptionTokenResponse = {
  token: string;
};

export type LabourSummaryDTO = {
  id: string;
  duration: number;
  contraction_count: number;
  current_phase: string;
  hospital_recommended: boolean;
};

export type LabourSummaryResponse = {
  labour: LabourSummaryDTO;
};

export type LabourUpdateDTO = {
  id: string;
  labour_update_type: string;
  labour_id: string;
  message: string;
  sent_time: string;
  edited: boolean;
  application_generated: boolean;
};

export type LabourUpdateRequest = {
  labour_update_type: LabourUpdateType;
  message: string;
  sent_time?: string | null;
};

/**
 * Represents the different types of labour update
 */
export type LabourUpdateType = 'announcement' | 'status_update' | 'private_note';

export type PlanLabourRequest = {
  first_labour: boolean;
  due_date: string;
  labour_name?: string | null;
};

export type RemoveSubscriberRequest = {
  subscription_id: string;
};

export type SendInviteRequest = {
  invite_email: string;
  labour_id: string;
};

export type SendSubscriberInviteRequest = {
  invite_email: string;
};

export type StartContractionRequest = {
  intensity?: number | null;
  start_time?: string | null;
  notes?: string | null;
};

export type SubscriberSubscriptionsResponse = {
  subscriptions: Array<SubscriptionDTO>;
  birthing_persons: Array<UserSummaryDTO>;
};

export type SubscribeToRequest = {
  token: string;
};

export type SubscriptionDataResponse = {
  subscription: SubscriptionDTO;
  birthing_person: UserSummaryDTO;
  labour: LabourDTO;
};

export type SubscriptionDTO = {
  id: string;
  labour_id: string;
  birthing_person_id: string;
  subscriber_id: string;
  role: string;
  status: string;
  access_level: string;
  contact_methods: Array<string>;
};

export type SubscriptionResponse = {
  subscription: SubscriptionDTO;
};

export type SubscriptionsResponse = {
  subscriptions: Array<SubscriptionDTO>;
};

export type TokenResponse = {
  access_token: string;
  token_type?: string;
};

export type UnblockSubscriberRequest = {
  subscription_id: string;
};

export type UnsubscribeFromRequest = {
  labour_id: string;
};

export type UpdateContactMethodsRequest = {
  subscription_id: string;
  contact_methods: Array<string>;
};

export type UpdateContractionRequest = {
  contraction_id: string;
  start_time?: string | null;
  end_time?: string | null;
  intensity?: number | null;
  notes?: string | null;
};

export type UpdateLabourUpdateRequest = {
  labour_update_id: string;
  labour_update_type?: LabourUpdateType | null;
  message?: string | null;
};

export type UpdateRoleRequest = {
  subscription_id: string;
  role: string;
};

export type UserDTO = {
  id: string;
  username: string;
  first_name: string;
  last_name: string;
  email: string;
  phone_number: string | null;
};

export type UserResponse = {
  user: UserDTO;
};

export type UserSummaryDTO = {
  id: string;
  first_name: string;
  last_name: string;
};

export type UserSummaryResponse = {
  user: UserSummaryDTO;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type LoginApiV1AuthLoginPostData = {
  formData: Body_login_api_v1_auth_login_post;
};

export type LoginApiV1AuthLoginPostResponse = TokenResponse;

export type StartContractionApiV1LabourContractionStartPostData = {
  requestBody: StartContractionRequest;
};

export type StartContractionApiV1LabourContractionStartPostResponse = LabourResponse;

export type EndContractionApiV1LabourContractionEndPutData = {
  requestBody: EndContractionRequest;
};

export type EndContractionApiV1LabourContractionEndPutResponse = LabourResponse;

export type UpdateContractionApiV1LabourContractionUpdatePutData = {
  requestBody: UpdateContractionRequest;
};

export type UpdateContractionApiV1LabourContractionUpdatePutResponse = LabourResponse;

export type DeleteContractionApiV1LabourContractionDeleteDeleteData = {
  requestBody: DeleteContractionRequest;
};

export type DeleteContractionApiV1LabourContractionDeleteDeleteResponse = LabourResponse;

export type RedirectToDocsGetResponse = unknown;

export type DocsDocsGetResponse = unknown;

export type OpenapiOpenapiJsonGetResponse = {
  [key: string]: unknown;
};

export type RedocRedocGetResponse = unknown;

export type HealthcheckApiV1HealthGetResponse = {
  [key: string]: string;
};

export type UpdateLabourPlanApiV1LabourPlanPutData = {
  requestBody: PlanLabourRequest;
};

export type UpdateLabourPlanApiV1LabourPlanPutResponse = LabourResponse;

export type PlanLabourApiV1LabourPlanPostData = {
  requestBody: PlanLabourRequest;
};

export type PlanLabourApiV1LabourPlanPostResponse = LabourResponse;

export type BeginLabourApiV1LabourBeginPostResponse = LabourResponse;

export type CompleteLabourApiV1LabourCompletePutData = {
  requestBody: CompleteLabourRequest;
};

export type CompleteLabourApiV1LabourCompletePutResponse = LabourResponse;

export type DeleteLabourApiV1LabourDeleteLabourIdDeleteData = {
  labourId: string;
};

export type DeleteLabourApiV1LabourDeleteLabourIdDeleteResponse = unknown | void;

export type GetSubscriptionTokenApiV1LabourSubscriptionTokenGetResponse =
  LabourSubscriptionTokenResponse;

export type SendInviteApiV1LabourSendInvitePostData = {
  requestBody: SendInviteRequest;
};

export type SendInviteApiV1LabourSendInvitePostResponse = void;

export type GetAllLaboursApiV1LabourGetAllGetResponse = LabourListResponse;

export type GetLabourByIdApiV1LabourGetLabourIdGetData = {
  labourId: string;
};

export type GetLabourByIdApiV1LabourGetLabourIdGetResponse = LabourResponse;

export type GetActiveLabourApiV1LabourActiveGetResponse = LabourResponse;

export type GetActiveLabourSummaryApiV1LabourActiveSummaryGetResponse = LabourSummaryResponse;

export type UpdateLabourUpdateApiV1LabourLabourUpdatePutData = {
  requestBody: UpdateLabourUpdateRequest;
};

export type UpdateLabourUpdateApiV1LabourLabourUpdatePutResponse = LabourResponse;

export type PostLabourUpdateApiV1LabourLabourUpdatePostData = {
  requestBody: LabourUpdateRequest;
};

export type PostLabourUpdateApiV1LabourLabourUpdatePostResponse = LabourResponse;

export type DeleteLabourUpdateApiV1LabourLabourUpdateDeleteData = {
  requestBody: DeleteLabourUpdateRequest;
};

export type DeleteLabourUpdateApiV1LabourLabourUpdateDeleteResponse = LabourResponse;

export type StripeWebhookApiV1PaymentsWebhookPostResponse = unknown;

export type CreateCheckoutSessionApiV1PaymentsCreateCheckoutSessionPostData = {
  requestBody: CreateCheckoutRequest;
};

export type CreateCheckoutSessionApiV1PaymentsCreateCheckoutSessionPostResponse = CheckoutResponse;

export type SendInviteApiV1SubscriberSendInvitePostData = {
  requestBody: SendSubscriberInviteRequest;
};

export type SendInviteApiV1SubscriberSendInvitePostResponse = void;

export type SubscribeToApiV1SubscriptionSubscribeLabourIdPostData = {
  labourId: string;
  requestBody: SubscribeToRequest;
};

export type SubscribeToApiV1SubscriptionSubscribeLabourIdPostResponse = SubscriptionResponse;

export type UnsubscribeFromApiV1SubscriptionUnsubscribePostData = {
  requestBody: UnsubscribeFromRequest;
};

export type UnsubscribeFromApiV1SubscriptionUnsubscribePostResponse = SubscriptionResponse;

export type GetSubscriptionsApiV1SubscriptionSubscriptionsGetResponse = SubscriptionsResponse;

export type GetSubscriberSubscriptionsApiV1SubscriptionSubscriberSubscriptionsGetResponse =
  SubscriberSubscriptionsResponse;

export type GetSubscriptionByIdApiV1SubscriptionSubscriptionDataSubscriptionIdGetData = {
  subscriptionId: string;
};

export type GetSubscriptionByIdApiV1SubscriptionSubscriptionDataSubscriptionIdGetResponse =
  SubscriptionDataResponse;

export type GetLabourSubscriptionsApiV1SubscriptionLabourSubscriptionsLabourIdGetData = {
  labourId: string;
};

export type GetLabourSubscriptionsApiV1SubscriptionLabourSubscriptionsLabourIdGetResponse =
  LabourSubscriptionsResponse;

export type ApproveSubscriberApiV1SubscriptionManagementApproveSubscriberPutData = {
  requestBody: ApproveSubscriberRequest;
};

export type ApproveSubscriberApiV1SubscriptionManagementApproveSubscriberPutResponse =
  SubscriptionResponse;

export type RemoveSubscriberApiV1SubscriptionManagementRemoveSubscriberPutData = {
  requestBody: RemoveSubscriberRequest;
};

export type RemoveSubscriberApiV1SubscriptionManagementRemoveSubscriberPutResponse =
  SubscriptionResponse;

export type BlockSubscriberApiV1SubscriptionManagementBlockSubscriberPutData = {
  requestBody: BlockSubscriberRequest;
};

export type BlockSubscriberApiV1SubscriptionManagementBlockSubscriberPutResponse =
  SubscriptionResponse;

export type UnblockSubscriberApiV1SubscriptionManagementUnblockSubscriberPutData = {
  requestBody: UnblockSubscriberRequest;
};

export type UnblockSubscriberApiV1SubscriptionManagementUnblockSubscriberPutResponse =
  SubscriptionResponse;

export type UpdateRoleApiV1SubscriptionManagementUpdateRolePutData = {
  requestBody: UpdateRoleRequest;
};

export type UpdateRoleApiV1SubscriptionManagementUpdateRolePutResponse = SubscriptionResponse;

export type UpdateContactMethodsApiV1SubscriptionManagementUpdateContactMethodsPutData = {
  requestBody: UpdateContactMethodsRequest;
};

export type UpdateContactMethodsApiV1SubscriptionManagementUpdateContactMethodsPutResponse =
  SubscriptionResponse;

export type GetUserApiV1UserGetResponse = UserResponse;

export type GetUserSummaryApiV1UserSummaryGetResponse = UserSummaryResponse;
