[package]
name = "notification_service_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = {version = "0.8.3"}
http-body-util = "=0.1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44", features = ["full"] }
