// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_api_v1_auth_login_post = {
  username: string;
  password: string;
};

export type ContactUsRequest = {
  category: string;
  email: string;
  name: string;
  message: string;
  token: string;
  data?: {
    [key: string]: unknown;
  } | null;
  user_id?: string | null;
};

export type ExceptionSchema = {
  description: string;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type TokenResponse = {
  access_token: string;
  token_type?: string;
};

export type UserDTO = {
  id: string;
  username: string;
  first_name: string;
  last_name: string;
  email: string;
  phone_number: string | null;
};

export type UserResponse = {
  user: UserDTO;
};

export type UserSummaryDTO = {
  id: string;
  first_name: string;
  last_name: string;
};

export type UserSummaryResponse = {
  user: UserSummaryDTO;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type LoginApiV1AuthLoginPostData = {
  formData: Body_login_api_v1_auth_login_post;
};

export type LoginApiV1AuthLoginPostResponse = TokenResponse;

export type ContactUsSendMessageApiV1ContactUsPostData = {
  requestBody: ContactUsRequest;
};

export type ContactUsSendMessageApiV1ContactUsPostResponse = void;

export type ContactUsStoreApiV1ContactUsStorePostData = {
  requestBody: ContactUsRequest;
};

export type ContactUsStoreApiV1ContactUsStorePostResponse = unknown;

export type RedirectToDocsGetResponse = unknown;

export type DocsDocsGetResponse = unknown;

export type OpenapiOpenapiJsonGetResponse = {
  [key: string]: unknown;
};

export type RedocRedocGetResponse = unknown;

export type HealthcheckApiV1HealthGetResponse = {
  [key: string]: string;
};

export type GetUserApiV1UserGetResponse = UserResponse;

export type GetUserSummaryApiV1UserSummaryGetResponse = UserSummaryResponse;
