// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { RegisterApiV1BirthingPersonRegisterPostData, RegisterApiV1BirthingPersonRegisterPostResponse, GetBirthingPersonApiV1BirthingPersonGetResponse, GetSubscriptionTokenApiV1BirthingPersonSubscriptionTokenGetResponse, RedirectToDocsGetResponse, HealthcheckApiV1HealthGetResponse, BeginLabourApiV1LabourBeginPostData, BeginLabourApiV1LabourBeginPostResponse, StartContractionApiV1LabourContractionStartPostData, StartContractionApiV1LabourContractionStartPostResponse, EndContractionApiV1LabourContractionEndPutData, EndContractionApiV1LabourContractionEndPutResponse, CompleteLabourApiV1LabourCompletePutData, CompleteLabourApiV1LabourCompletePutResponse, GetActiveLabourApiV1LabourActiveGetResponse, GetActiveLabourSummaryApiV1LabourActiveSummaryGetResponse, RegisterApiV1SubscriberRegisterPostData, RegisterApiV1SubscriberRegisterPostResponse, GetBirthingPersonApiV1SubscriberSubscribeToBirthingPersonIdPostData, GetBirthingPersonApiV1SubscriberSubscribeToBirthingPersonIdPostResponse } from './types.gen';

export class BirthingPersonService {
    /**
     * Register
     * @param data The data for the request.
     * @param data.requestBody
     * @returns BirthingPersonResponse Successful Response
     * @throws ApiError
     */
    public static registerApiV1BirthingPersonRegisterPost(data: RegisterApiV1BirthingPersonRegisterPostData): CancelablePromise<RegisterApiV1BirthingPersonRegisterPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/birthing-person/register',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Bad Request',
                401: 'Unauthorized',
                404: 'Not Found',
                422: 'Validation Error',
                500: 'Internal Server Error'
            }
        });
    }
    
    /**
     * Get Birthing Person
     * @returns BirthingPersonResponse Successful Response
     * @throws ApiError
     */
    public static getBirthingPersonApiV1BirthingPersonGet(): CancelablePromise<GetBirthingPersonApiV1BirthingPersonGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/birthing-person/',
            errors: {
                400: 'Bad Request',
                401: 'Unauthorized',
                404: 'Not Found',
                500: 'Internal Server Error'
            }
        });
    }
    
    /**
     * Get Subscription Token
     * @returns BirthingPersonSubscriptionTokenResponse Successful Response
     * @throws ApiError
     */
    public static getSubscriptionTokenApiV1BirthingPersonSubscriptionTokenGet(): CancelablePromise<GetSubscriptionTokenApiV1BirthingPersonSubscriptionTokenGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/birthing-person/subscription-token',
            errors: {
                400: 'Bad Request',
                401: 'Unauthorized',
                404: 'Not Found',
                500: 'Internal Server Error'
            }
        });
    }
    
}

export class GeneralService {
    /**
     * Redirect To Docs
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static redirectToDocsGet(): CancelablePromise<RedirectToDocsGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/'
        });
    }
    
}

export class HealthService {
    /**
     * Healthcheck
     * @returns string Successful Response
     * @throws ApiError
     */
    public static checkApiV1HealthGet(): CancelablePromise<HealthcheckApiV1HealthGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/health'
        });
    }
    
}

export class LabourTrackingService {
    /**
     * Begin Labour
     * Begin labour for the current user
     * @param data The data for the request.
     * @param data.requestBody
     * @returns LabourResponse Successful Response
     * @throws ApiError
     */
    public static beginLabourApiV1LabourBeginPost(data: BeginLabourApiV1LabourBeginPostData): CancelablePromise<BeginLabourApiV1LabourBeginPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/labour/begin',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Bad Request',
                401: 'Unauthorized',
                404: 'Not Found',
                422: 'Validation Error',
                500: 'Internal Server Error'
            }
        });
    }
    
    /**
     * Start Contraction
     * Start a new contraction in the given labor session
     * @param data The data for the request.
     * @param data.requestBody
     * @returns LabourResponse Successful Response
     * @throws ApiError
     */
    public static startContractionApiV1LabourContractionStartPost(data: StartContractionApiV1LabourContractionStartPostData): CancelablePromise<StartContractionApiV1LabourContractionStartPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/labour/contraction/start',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Bad Request',
                401: 'Unauthorized',
                404: 'Not Found',
                422: 'Validation Error',
                500: 'Internal Server Error'
            }
        });
    }
    
    /**
     * End Contraction
     * End the currently active contraction in the given session
     * @param data The data for the request.
     * @param data.requestBody
     * @returns LabourResponse Successful Response
     * @throws ApiError
     */
    public static endContractionApiV1LabourContractionEndPut(data: EndContractionApiV1LabourContractionEndPutData): CancelablePromise<EndContractionApiV1LabourContractionEndPutResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/labour/contraction/end',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Bad Request',
                401: 'Unauthorized',
                404: 'Not Found',
                422: 'Validation Error',
                500: 'Internal Server Error'
            }
        });
    }
    
    /**
     * Complete Labour
     * Mark a labor session as complete
     * @param data The data for the request.
     * @param data.requestBody
     * @returns LabourResponse Successful Response
     * @throws ApiError
     */
    public static completeLabourApiV1LabourCompletePut(data: CompleteLabourApiV1LabourCompletePutData): CancelablePromise<CompleteLabourApiV1LabourCompletePutResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/labour/complete',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Bad Request',
                401: 'Unauthorized',
                404: 'Not Found',
                422: 'Validation Error',
                500: 'Internal Server Error'
            }
        });
    }
    
    /**
     * Get Active Labour
     * @returns LabourResponse Successful Response
     * @throws ApiError
     */
    public static getActiveLabourApiV1LabourActiveGet(): CancelablePromise<GetActiveLabourApiV1LabourActiveGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/labour/active',
            errors: {
                400: 'Bad Request',
                401: 'Unauthorized',
                404: 'Not Found',
                500: 'Internal Server Error'
            }
        });
    }
    
    /**
     * Get Active Labour Summary
     * @returns LabourSummaryResponse Successful Response
     * @throws ApiError
     */
    public static getActiveLabourSummaryApiV1LabourActiveSummaryGet(): CancelablePromise<GetActiveLabourSummaryApiV1LabourActiveSummaryGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/labour/active/summary',
            errors: {
                400: 'Bad Request',
                401: 'Unauthorized',
                404: 'Not Found',
                500: 'Internal Server Error'
            }
        });
    }
    
}

export class SubscriberService {
    /**
     * Register
     * @param data The data for the request.
     * @param data.requestBody
     * @returns SubscriberResponse Successful Response
     * @throws ApiError
     */
    public static registerApiV1SubscriberRegisterPost(data: RegisterApiV1SubscriberRegisterPostData): CancelablePromise<RegisterApiV1SubscriberRegisterPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/subscriber/register',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Bad Request',
                401: 'Unauthorized',
                404: 'Not Found',
                422: 'Validation Error',
                500: 'Internal Server Error'
            }
        });
    }
    
    /**
     * Get Birthing Person
     * @param data The data for the request.
     * @param data.birthingPersonId
     * @param data.requestBody
     * @returns SubscriberResponse Successful Response
     * @throws ApiError
     */
    public static getBirthingPersonApiV1SubscriberSubscribeToBirthingPersonIdPost(data: GetBirthingPersonApiV1SubscriberSubscribeToBirthingPersonIdPostData): CancelablePromise<GetBirthingPersonApiV1SubscriberSubscribeToBirthingPersonIdPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/subscriber/subscribe_to/{birthing_person_id}',
            path: {
                birthing_person_id: data.birthingPersonId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Bad Request',
                401: 'Unauthorized',
                404: 'Not Found',
                422: 'Validation Error',
                500: 'Internal Server Error'
            }
        });
    }
    
}