// This file is auto-generated by @hey-api/openapi-ts

export type BlockSubscriberRequest = {
  subscription_id: string;
};

export type Body_login_api_v1_auth_login_post = {
  username: string;
  password: string;
};

export type CompleteLabourRequest = {
  end_time?: string | null;
  notes?: string | null;
};

export type ContactUsRequest = {
  email: string;
  name: string;
  message: string;
  token: string;
  user_id?: string | null;
};

export type ContractionDTO = {
  id: string;
  labour_id: string;
  start_time: string;
  end_time: string;
  duration: number;
  intensity: number | null;
  notes: string | null;
  is_active: boolean;
};

export type EndContractionRequest = {
  intensity: number;
  end_time?: string | null;
  notes?: string | null;
};

export type ExceptionSchema = {
  description: string;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type LabourDTO = {
  id: string;
  birthing_person_id: string;
  current_phase: string;
  due_date: string;
  first_labour: boolean;
  labour_name: string | null;
  start_time: string | null;
  end_time: string | null;
  notes: string | null;
  recommendations: {
    [key: string]: boolean;
  };
  contractions: Array<ContractionDTO>;
  announcements: Array<LabourUpdateDTO>;
  status_updates: Array<LabourUpdateDTO>;
};

export type LabourResponse = {
  labour: LabourDTO;
};

export type LabourSubscriptionsResponse = {
  subscriptions: Array<SubscriptionDTO>;
  subscribers: Array<UserSummaryDTO>;
};

export type LabourSubscriptionTokenResponse = {
  token: string;
};

export type LabourSummaryDTO = {
  id: string;
  duration: number;
  contraction_count: number;
  current_phase: string;
  hospital_recommended: boolean;
};

export type LabourSummaryResponse = {
  labour: LabourSummaryDTO;
};

export type LabourUpdateDTO = {
  id: string;
  labour_update_type: string;
  labour_id: string;
  message: string;
  sent_time: string;
};

export type LabourUpdateRequest = {
  labour_update_type: LabourUpdateType;
  message: string;
  sent_time?: string | null;
};

/**
 * Represents the different types of labour update
 */
export type LabourUpdateType = 'announcement' | 'status_update';

export type PlanLabourRequest = {
  first_labour: boolean;
  due_date: string;
  labour_name?: string | null;
};

export type RemoveSubscriberRequest = {
  subscription_id: string;
};

export type SendInviteRequest = {
  invite_email: string;
  labour_id: string;
};

export type StartContractionRequest = {
  intensity?: number | null;
  start_time?: string | null;
  notes?: string | null;
};

export type SubscriberSubscriptionsResponse = {
  subscriptions: Array<SubscriptionDTO>;
  birthing_persons: Array<UserSummaryDTO>;
};

export type SubscribeToRequest = {
  token: string;
};

export type SubscriptionDataResponse = {
  subscription: SubscriptionDTO;
  birthing_person: UserSummaryDTO;
  labour: LabourDTO;
};

export type SubscriptionDTO = {
  id: string;
  labour_id: string;
  birthing_person_id: string;
  subscriber_id: string;
  role: string;
  status: string;
  contact_methods: Array<string>;
};

export type SubscriptionResponse = {
  subscription: SubscriptionDTO;
};

export type SubscriptionsResponse = {
  subscriptions: Array<SubscriptionDTO>;
};

export type TokenResponse = {
  access_token: string;
  token_type?: string;
};

export type UnsubscribeFromRequest = {
  labour_id: string;
};

export type UpdateContactMethodsRequest = {
  subscription_id: string;
  contact_methods: Array<string>;
};

export type UpdateRoleRequest = {
  subscription_id: string;
  role: string;
};

export type UserDTO = {
  id: string;
  username: string;
  first_name: string;
  last_name: string;
  email: string;
  phone_number: string | null;
};

export type UserResponse = {
  user: UserDTO;
};

export type UserSummaryDTO = {
  id: string;
  first_name: string;
  last_name: string;
};

export type UserSummaryResponse = {
  user: UserSummaryDTO;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type LoginApiV1AuthLoginPostData = {
  formData: Body_login_api_v1_auth_login_post;
};

export type LoginApiV1AuthLoginPostResponse = TokenResponse;

export type GetUserApiV1AuthUserGetResponse = UserDTO;

export type ContactUsSendMessageApiV1ContactUsPostData = {
  requestBody: ContactUsRequest;
};

export type ContactUsSendMessageApiV1ContactUsPostResponse = void;

export type RedirectToDocsGetResponse = unknown;

export type HealthcheckApiV1HealthGetResponse = {
  [key: string]: string;
};

export type GetLabourByIdApiV1LabourGetLabourIdGetData = {
  labourId: string;
};

export type GetLabourByIdApiV1LabourGetLabourIdGetResponse = LabourResponse;

export type UpdateLabourPlanApiV1LabourPlanPutData = {
  requestBody: PlanLabourRequest;
};

export type UpdateLabourPlanApiV1LabourPlanPutResponse = LabourResponse;

export type PlanLabourApiV1LabourPlanPostData = {
  requestBody: PlanLabourRequest;
};

export type PlanLabourApiV1LabourPlanPostResponse = LabourResponse;

export type BeginLabourApiV1LabourBeginPostResponse = LabourResponse;

export type StartContractionApiV1LabourContractionStartPostData = {
  requestBody: StartContractionRequest;
};

export type StartContractionApiV1LabourContractionStartPostResponse = LabourResponse;

export type EndContractionApiV1LabourContractionEndPutData = {
  requestBody: EndContractionRequest;
};

export type EndContractionApiV1LabourContractionEndPutResponse = LabourResponse;

export type CompleteLabourApiV1LabourCompletePutData = {
  requestBody: CompleteLabourRequest;
};

export type CompleteLabourApiV1LabourCompletePutResponse = LabourResponse;

export type GetActiveLabourApiV1LabourActiveGetResponse = LabourResponse;

export type GetActiveLabourSummaryApiV1LabourActiveSummaryGetResponse = LabourSummaryResponse;

export type PostLabourUpdateApiV1LabourLabourUpdatePostData = {
  requestBody: LabourUpdateRequest;
};

export type PostLabourUpdateApiV1LabourLabourUpdatePostResponse = LabourResponse;

export type GetSubscriptionTokenApiV1LabourSubscriptionTokenGetResponse =
  LabourSubscriptionTokenResponse;

export type SendInviteApiV1LabourSendInvitePostData = {
  requestBody: SendInviteRequest;
};

export type SendInviteApiV1LabourSendInvitePostResponse = void;

export type SubscribeToApiV1SubscriptionSubscribeLabourIdPostData = {
  labourId: string;
  requestBody: SubscribeToRequest;
};

export type SubscribeToApiV1SubscriptionSubscribeLabourIdPostResponse = SubscriptionResponse;

export type UnsubscribeFromApiV1SubscriptionUnsubscribePostData = {
  requestBody: UnsubscribeFromRequest;
};

export type UnsubscribeFromApiV1SubscriptionUnsubscribePostResponse = SubscriptionResponse;

export type GetSubscriptionsApiV1SubscriptionSubscriptionsGetResponse = SubscriptionsResponse;

export type GetSubscriberSubscriptionsApiV1SubscriptionSubscriberSubscriptionsGetResponse =
  SubscriberSubscriptionsResponse;

export type GetSubscriptionByIdApiV1SubscriptionSubscriptionDataSubscriptionIdGetData = {
  subscriptionId: string;
};

export type GetSubscriptionByIdApiV1SubscriptionSubscriptionDataSubscriptionIdGetResponse =
  SubscriptionDataResponse;

export type GetLabourSubscriptionsApiV1SubscriptionLabourSubscriptionsLabourIdGetData = {
  labourId: string;
};

export type GetLabourSubscriptionsApiV1SubscriptionLabourSubscriptionsLabourIdGetResponse =
  LabourSubscriptionsResponse;

export type RemoveSubscriberApiV1SubscriptionManagementRemoveSubscriberPutData = {
  requestBody: RemoveSubscriberRequest;
};

export type RemoveSubscriberApiV1SubscriptionManagementRemoveSubscriberPutResponse =
  SubscriptionResponse;

export type BlockSubscriberApiV1SubscriptionManagementBlockSubscriberPutData = {
  requestBody: BlockSubscriberRequest;
};

export type BlockSubscriberApiV1SubscriptionManagementBlockSubscriberPutResponse =
  SubscriptionResponse;

export type UpdateRoleApiV1SubscriptionManagementUpdateRolePutData = {
  requestBody: UpdateRoleRequest;
};

export type UpdateRoleApiV1SubscriptionManagementUpdateRolePutResponse = SubscriptionResponse;

export type UpdateContactMethodsApiV1SubscriptionManagementUpdateContactMethodsPutData = {
  requestBody: UpdateContactMethodsRequest;
};

export type UpdateContactMethodsApiV1SubscriptionManagementUpdateContactMethodsPutResponse =
  SubscriptionResponse;

export type GetUserApiV1UserGetResponse = UserResponse;

export type GetUserSummaryApiV1UserSummaryGetResponse = UserSummaryResponse;
