"""added_labour_attributes

Revision ID: 965371c06219
Revises: 6894d33d448c
Create Date: 2025-02-17 12:23:58.506905

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "965371c06219"
down_revision: str | None = "6894d33d448c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("labours", sa.Column("due_date", sa.DateTime(timezone=True), nullable=True))
    op.add_column("labours", sa.Column("labour_name", sa.String(), nullable=True))
    op.alter_column(
        "labours", "start_time", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="labour_phase",
        new_values=["PLANNED", "EARLY", "ACTIVE", "TRANSITION", "PUSHING", "COMPLETE"],
        affected_columns=[
            TableReference(table_schema="public", table_name="labours", column_name="current_phase")
        ],
        enum_values_to_rename=[],
    )
    # Copy the value from start_time to due_date
    op.execute("UPDATE labours SET due_date = start_time")
    # Make due_date nullable=False
    op.alter_column("labours", "due_date", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="labour_phase",
        new_values=["EARLY", "ACTIVE", "TRANSITION", "PUSHING", "COMPLETE"],
        affected_columns=[
            TableReference(table_schema="public", table_name="labours", column_name="current_phase")
        ],
        enum_values_to_rename=[],
    )
    op.alter_column(
        "labours", "start_time", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False
    )
    op.drop_column("labours", "labour_name")
    op.drop_column("labours", "due_date")
    # ### end Alembic commands ###
