"""Rename notification type to notification channel

Revision ID: 1db70670d54e
Revises: 39b6ef13aecf
Create Date: 2025-04-26 21:40:34.741113

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1db70670d54e"
down_revision: str | None = "39b6ef13aecf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    sa.Enum("EMAIL", "SMS", name="notification_channel").create(op.get_bind())

    op.execute(
        """
        ALTER TABLE notifications
        ALTER COLUMN type TYPE notification_channel
        USING type::text::notification_channel
        """
    )

    op.alter_column("notifications", "type", new_column_name="channel")

    sa.Enum("EMAIL", "SMS", name="notification_type").drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    sa.Enum("EMAIL", "SMS", name="notification_type").create(op.get_bind())

    op.execute(
        """
        ALTER TABLE notifications
        ALTER COLUMN channel TYPE notification_type
        USING channel::text::notification_type
        """
    )
    op.alter_column("notifications", "channel", new_column_name="type")

    sa.Enum("EMAIL", "SMS", name="notification_channel").drop(op.get_bind())
    # ### end Alembic commands ###
