"""empty message

Revision ID: 22b4deb6e293
Revises: 1db70670d54e
Create Date: 2025-04-27 21:51:40.958382

"""

from collections.abc import Sequence

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "22b4deb6e293"
down_revision: str | None = "1db70670d54e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="notification_channel",
        new_values=["EMAIL", "SMS", "WHATSAPP"],
        affected_columns=[
            TableReference(table_schema="public", table_name="notifications", column_name="channel")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="notification_channel",
        new_values=["EMAIL", "SMS"],
        affected_columns=[
            TableReference(table_schema="public", table_name="notifications", column_name="channel")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
