"""Rename notification type to notification channel

Revision ID: 1db70670d54e
Revises: 39b6ef13aecf
Create Date: 2025-04-26 21:40:34.741113

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1db70670d54e"
down_revision: str | None = "39b6ef13aecf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("EMAIL", "SMS", name="notification_channel").create(op.get_bind())
    op.add_column(
        "notifications",
        sa.Column(
            "channel",
            postgresql.ENUM("EMAIL", "SMS", name="notification_channel", create_type=False),
            nullable=False,
        ),
    )
    op.drop_column("notifications", "type")
    sa.Enum("EMAIL", "SMS", name="notification_type").drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("EMAIL", "SMS", name="notification_type").create(op.get_bind())
    op.add_column(
        "notifications",
        sa.Column(
            "type",
            postgresql.ENUM("EMAIL", "SMS", name="notification_type", create_type=False),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("notifications", "channel")
    sa.Enum("EMAIL", "SMS", name="notification_channel").drop(op.get_bind())
    # ### end Alembic commands ###
