# Any values that are set in .env will replace these values.
[base]
ENVIRONMENT = ""
SUPPORT_EMAIL = "support@fernlabour.com"

[security.keycloak]
KEYCLOAK_SERVER_URL = "http://localhost:8080"
KEYCLOAK_DOCKER_URL = "http://keycloak:8080"
KEYCLOAK_REALM  = "labour_tracker"
KEYCLOAK_CLIENT_ID  = "labour_tracker_backend"
KEYCLOAK_CLIENT_SECRET  = "changeme"
KEYCLOAK_ADMIN = ""
KEYCLOAK_ADMIN_PASSWORD = ""
# JWT_ALGORITHM can be set to "HS256", "HS384", "HS512", "RS256", "RS384", "RS512"
JWT_ALGORITHM = "HS256"

[security.subscriber_token]
SUBSCRIBER_TOKEN_SALT = ""

[security.cloudflare]
CLOUDFLARE_URL = ""
CLOUDFLARE_SECRET_KEY = ""

[security.rate_limits]
LABOUR_INVITE_RATE_LIMIT = 20
LABOUR_INVITE_RATE_LIMIT_EXPIRY = 86400
SUBSCRIBER_INVITE_RATE_LIMIT = 20
SUBSCRIBER_INVITE_RATE_LIMIT_EXPIRY = 86400

[logging]
# Level can be set to "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
LOG_LEVEL = "INFO"


[uvicorn]
UVICORN_HOST = "0.0.0.0"
UVICORN_PORT = 8000
UVICORN_RELOAD = false


[db.postgres]
# Specify as in Docker network
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "changeme"
POSTGRES_DB = "app"
POSTGRES_HOST = "db"
POSTGRES_PORT = 5432


[db.sqla_engine]
SQLA_ECHO = false
SQLA_ECHO_POOL = false
SQLA_POOL_SIZE = 50
SQLA_MAX_OVERFLOW = 10


[structure]
CONFIG_TOML = "config.toml"
PYPROJECT_TOML = "pyproject.toml"


[security.cors]
BACKEND_CORS_ORIGINS = "http://localhost,https://localhost"
FRONTEND_HOST = "http://localhost:5173"
MARKETING_HOST = "http://localhost:3000"

[events.gcp]
GCP_PROJECT_ID = "test"
GCP_PRODUCER_RETRIES = 3

[payments.stripe]
STRIPE_API_KEY = ""
STRIPE_WEBHOOK_ENDPOINT_SECRET = ""

[redis]
REDIS_HOST = "valkey"
REDIS_PORT = 6379
REDIS_PASSWORD = ""
