SAMPLE_CONTRACTION_SIZE = 4

CONTRACTIONS_REQUIRED_NULLIPAROUS = 20
CONTRACTIONS_REQUIRED_PAROUS = 5

TIME_BETWEEN_CONTRACTIONS_NULLIPAROUS = 3
TIME_BETWEEN_CONTRACTIONS_PAROUS = 5

LENGTH_OF_CONTRACTIONS_MINUTES = 1
