"""Replace labour payment plan with subscription access level

Revision ID: 88cce3b3a8c3
Revises: 5304ea3b2244
Create Date: 2025-05-06 22:08:41.185072

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "88cce3b3a8c3"
down_revision: str | None = "5304ea3b2244"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("BASIC", "SUPPORTER", name="subscription_access_level").create(op.get_bind())
    op.drop_column("labours", "payment_plan")
    op.add_column(
        "subscriptions",
        sa.Column(
            "access_level",
            postgresql.ENUM(
                "BASIC", "SUPPORTER", name="subscription_access_level", create_type=False
            ),
            nullable=True,
        ),
    )
    op.execute("UPDATE subscriptions SET access_level = 'SUPPORTER'")
    op.alter_column("subscriptions", "access_level", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "access_level")
    op.add_column(
        "labours", sa.Column("payment_plan", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    sa.Enum("BASIC", "SUPPORTER", name="subscription_access_level").drop(op.get_bind())
    # ### end Alembic commands ###
