"""Add indexes for labour

Revision ID: ceb02c076c01
Revises: 8d2a499cd0cc
Create Date: 2025-05-26 16:37:17.859486

"""

from collections.abc import Sequence

from alembic import op

revision: str = "ceb02c076c01"
down_revision: str | None = "8d2a499cd0cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_index("idx_contractions_labour_id", "contractions", ["labour_id"])
    op.create_index("idx_labour_updates_labour_id", "labour_updates", ["labour_id"])

    op.create_index(
        "idx_contractions_labour_start_time", "contractions", ["labour_id", "start_time"]
    )
    op.create_index(
        "idx_labour_updates_labour_sent_time", "labour_updates", ["labour_id", "sent_time"]
    )

    op.create_index("idx_labours_birthing_person_id", "labours", ["birthing_person_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index("idx_labours_birthing_person_id", table_name="labours")
    op.drop_index("idx_labour_updates_labour_sent_time", table_name="labour_updates")
    op.drop_index("idx_contractions_labour_start_time", table_name="contractions")
    op.drop_index("idx_labour_updates_labour_id", table_name="labour_updates")
    op.drop_index("idx_contractions_labour_id", table_name="contractions")

    # ### end Alembic commands ###
