"""Add domain event table

Revision ID: 8da1729f2117
Revises: ceb02c076c01
Create Date: 2025-06-03 19:21:29.654720

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from src.core.infrastructure.persistence.domain_event.table import JSONEncryptedType

# revision identifiers, used by Alembic.
revision: str = "8da1729f2117"
down_revision: str | None = "ceb02c076c01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("aggregate_id", sa.String(), nullable=False),
        sa.Column("aggregate_type", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("data", JSONEncryptedType(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domain_events")),
    )
    op.create_index("idx_domain_events_event_id", "domain_events", ["event_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_domain_events_event_id", table_name="domain_events")
    op.drop_table("domain_events")
    # ### end Alembic commands ###
