"""Initial tables

Revision ID: 650910e5f92c
Revises:
Create Date: 2025-05-09 22:22:59.574263

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "650910e5f92c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("ERROR_REPORT", "IDEA", "TESTIMONIAL", "OTHER", name="contact_message_category").create(
        op.get_bind()
    )
    op.create_table(
        "contact_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "category",
            postgresql.ENUM(
                "ERROR_REPORT",
                "IDEA",
                "TESTIMONIAL",
                "OTHER",
                name="contact_message_category",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_messages")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contact_messages")
    sa.Enum("ERROR_REPORT", "IDEA", "TESTIMONIAL", "OTHER", name="contact_message_category").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###
