"""empty message

Revision ID: 46c842093dbf
Revises: 88cce3b3a8c3
Create Date: 2025-05-17 22:20:28.921836

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46c842093dbf"
down_revision: str | None = "88cce3b3a8c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("labour_updates", sa.Column("edited", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("labour_updates", "edited")
    # ### end Alembic commands ###
