"""add requested subscription status

Revision ID: 5304ea3b2244
Revises: 12068cca7365
Create Date: 2025-05-04 20:13:07.513505

"""

from collections.abc import Sequence

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "5304ea3b2244"
down_revision: str | None = "12068cca7365"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="subscription_status",
        new_values=["SUBSCRIBED", "UNSUBSCRIBED", "REQUESTED", "REMOVED", "BLOCKED"],
        affected_columns=[
            TableReference(table_schema="public", table_name="subscriptions", column_name="status")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="subscription_status",
        new_values=["SUBSCRIBED", "UNSUBSCRIBED", "REMOVED", "BLOCKED"],
        affected_columns=[
            TableReference(table_schema="public", table_name="subscriptions", column_name="status")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
