"""add private notes

Revision ID: 8d2a499cd0cc
Revises: 46c842093dbf
Create Date: 2025-05-19 16:53:06.333121

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "8d2a499cd0cc"
down_revision: str | None = "46c842093dbf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="labour_update_type",
        new_values=["ANNOUNCEMENT", "STATUS_UPDATE", "PRIVATE_NOTE"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="labour_updates", column_name="labour_update_type"
            )
        ],
        enum_values_to_rename=[],
    )
    op.add_column("labour_updates", sa.Column("application_generated", sa.Boolean(), nullable=True))
    op.execute("UPDATE labour_updates SET application_generated = false")
    op.alter_column("labour_updates", "application_generated", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="labour_update_type",
        new_values=["ANNOUNCEMENT", "STATUS_UPDATE"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="labour_updates", column_name="labour_update_type"
            )
        ],
        enum_values_to_rename=[],
    )
    op.drop_column("labour_updates", "application_generated")
    # ### end Alembic commands ###
