"""Add idempotency table

Revision ID: 8090ee268002
Revises: 8da1729f2117
Create Date: 2025-06-14 21:08:29.546151

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8090ee268002"
down_revision: str | None = "8da1729f2117"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("PROCESSING", "COMPLETED", name="processing_status_enum").create(op.get_bind())
    op.create_table(
        "consumer_processed_events",
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PROCESSING", "COMPLETED", name="processing_status_enum", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_consumer_processed_events")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("consumer_processed_events")
    sa.Enum("PROCESSING", "COMPLETED", name="processing_status_enum").drop(op.get_bind())
    # ### end Alembic commands ###
