name: Deploy Frontend to Cloudflare Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: './frontend/.nvmrc'

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run build
        run: npm run build
        working-directory: ./frontend
        env:
          VITE_LABOUR_SERVICE_URL: ${{ vars.LABOUR_SERVICE_URL }}
          VITE_CONTACT_SERVICE_URL: ${{ vars.CONTACT_SERVICE_URL }}
          VITE_KEYCLOAK_AUTHORITY: ${{ vars.VITE_KEYCLOAK_AUTHORITY }}
          VITE_KEYCLOAK_METADATA_URL: ${{ vars.VITE_KEYCLOAK_METADATA_URL }}
          VITE_KEYCLOAK_CLIENT_ID: ${{ vars.VITE_KEYCLOAK_CLIENT_ID }}
          VITE_POST_LOGOUT_REDIRECT: ${{ vars.MARKETING_URL }}

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PAGES_FRONTEND_PROJECT }}
          directory: ./frontend/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}