name: Deploy Marketing to Cloudflare Pages

on:
  push:
    branches: ['main']
    paths:
      - 'marketing/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: './marketing/.nvmrc'

      - name: Install dependencies
        run: npm ci
        working-directory: ./marketing

      - name: Run build
        run: npm run build
        working-directory: ./marketing
        env:
          NEXT_PUBLIC_CONTACT_SERVICE_URL: ${{ vars.CONTACT_SERVICE_URL }}
          NEXT_PUBLIC_FRONTEND_URL: ${{ vars.FRONTEND_URL }}
          NEXT_PUBLIC_INSTAGRAM_URL: ${{ vars.INSTAGRAM_URL }}
          NEXT_PUBLIC_CLOUDFLARE_SITEKEY: ${{ vars.CLOUDFLARE_SITEKEY }}

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PAGES_MARKETING_PROJECT }}
          directory: ./marketing/out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}