name: Labour Service Checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'labour_service/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v4
        with:
          version: "0.6.3"
          enable-cache: true
      - name: Run tests
        run: uv run pytest --cov
        working-directory: ./labour_service

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v4
        with:
          version: "0.6.3"
          enable-cache: true
      - name: Run MyPy
        run: uv run mypy app
        working-directory: ./labour_service
      - name: Run Ruff Check
        run: uv run ruff check app
        working-directory: ./labour_service
      - name: Run Ruff Format Check
        run: uv run ruff format app --check
        working-directory: ./labour_service