name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.5"
          enable-cache: true

      - name: Check MyPy version
        run: uv run mypy --version
        working-directory: ./backend

      - name: Check Ruff version
        run: uv run ruff --version
        working-directory: ./backend

      - name: Run MyPy
        run: uv run mypy app
        working-directory: ./backend

      - name: Run Ruff Check
        run: uv run ruff check app
        working-directory: ./backend

      - name: Run Ruff Format Check
        run: uv run ruff format app --check
        working-directory: ./backend
