name: Test Backend

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.5"
          enable-cache: true

      - name: sync
        run: uv sync --all-groups
        working-directory: .

      - name: Run tests
        run: uv run coverage run -m pytest && coverage html "Coverage for ${{ github.sha }}"
        working-directory: .

      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: ./htmlcov
          include-hidden-files: true
