name: Test Frontend

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'frontend/**'
      - '.github/workflows/**'

jobs:
  test-frontend-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: './frontend/.nvmrc'

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run build
        run: npm run build
        working-directory: ./frontend

      - name: Run tests
        run: npm test
        working-directory: ./frontend
